name: memail
description: Email yourself a link in a single tap.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.3.0
  share_intent_package: ^1.0.29
  intl: ^0.19.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  google_sign_in: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_foreground: "assets/android-icon-foreground.png"
  adaptive_icon_background: "assets/android-icon-background.png"
  adaptive_icon_monochrome: "assets/android-icon-monochrome.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
